CREATE SCHEMA IF NOT EXISTS WorkplaceDB;
USE WorkplaceDB;

DROP TABLE IF EXISTS Salaries;

CREATE TABLE Salaries(
  `row_num` INT AUTO_INCREMENT PRIMARY KEY,
  `first_name` VARCHAR(20) NOT NULL,
  `last_name` VARCHAR(20) NOT NULL,
  `salary` DECIMAL NOT NULL
);
